<?php
include_once('Model/connect.php');
include_once('Model/user.php');
include_once('Model/regions.php');
include_once('Model/patients.php');
include_once('Model/cities.php');
include_once('Model/health_workers.php');
?>
<html>
<head>
</head>
</html>