<?php
include_once('Model/connect.php');
include_once('Model/user.php');
include_once('Model/regions.php');
include_once('Model/patients.php');
include_once('Model/cities.php');
include_once('Model/health_workers.php');
include_once('Model/facilities.php');
include_once('Model/groupzones.php');
include_once('Model/publichealthrecommendation.php');
include_once('Model/messages.php');
?>
<html>
<head>
</head>
</html>